import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "praneeth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="localFont">
        <div className="p-4  border-b">
          Navbar
        </div>
        {children}
      </body>
    </html>
  );
}
